FilmBuffs/Controllers/ExploreController.cs
using FilmBuffs.Database;
using FilmBuffs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmBuffs.Controllers
{
    public class ExploreController : Controller
    {
        // GET: Explore
        public ActionResult Index(int? pageIndex, string orderBy)
        {
            if (pageIndex == null || pageIndex < 1)
            {
                pageIndex = 1;
            }

            var model = new PagingModel<MovieModel>
            {
                CurrentPage = pageIndex.Value,
                PageSize = 10,
                OrderBy = orderBy == null ? string.Empty : orderBy.ToLower(),
                Records = new List<MovieModel>()

            };

            var dbContext = new FbDatabase();
            var dbMovies = dbContext.Movies.ToList();
            var moviesFromDatabase = dbContext.Movies.AsEnumerable();

            //ordering
            switch (model.OrderBy)
            {
                case "title":
                    moviesFromDatabase = moviesFromDatabase.OrderByDescending(e => e.Title).ToList();
                    break;
                case "year":
                    moviesFromDatabase = moviesFromDatabase.OrderByDescending(e => e.Year).ToList();
                    break;
                default:
                    moviesFromDatabase = moviesFromDatabase.OrderBy(e => e.Title).ToList();
                    break;
            }


            model.TotalRecord = moviesFromDatabase.Count();
            var dbMovieList = moviesFromDatabase.Skip((model.CurrentPage - 1) * model.PageSize).Take(model.PageSize).ToList();
            model.Records = dbMovieList.Select(e => new MovieModel(e)).ToList();

            return View(model);
        }
    }
}

FilmBuffs/Controllers/HomeController.cs
using FilmBuffs.Database;
using FilmBuffs.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmBuffs.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index(int? id)
        {
            var model = new HomeModel
            {
                Heading = "Film Buffs",
                Movies = new List<Models.MovieListModel>()

            };
            var dbContext = new FbDatabase();
            if (id > 0)
            {
                var genre = dbContext.Genres.FirstOrDefault(e => e.Id == id);
                if (genre != null)
                {
                    model.Heading = genre.Name;
                    model.Movies = dbContext.Movies.Where(e => e.GenreID == id).
                                    AsEnumerable().Select(e => new Models.MovieListModel(e)).ToList();
                }
            }
            else
            {
                model.Movies = dbContext.Movies.AsEnumerable().Select(e => new Models.MovieListModel(e)).Take(5).ToList();
                
            }

            return View(model);
        }

        public ActionResult Search (string keyword)
        {

            var model = new SearchModel<MovieModel>
            {
                Keyword = keyword,
                Records = new List<MovieModel>()
            };

            var dbContext = new FbDatabase();
            var dbMovies = dbContext.Movies.ToList();
            var moviesFromDatabase = dbContext.Movies.AsEnumerable();

            if (!string.IsNullOrEmpty(keyword))
            {
                model.Keyword = model.Keyword.Trim().ToLower();
                moviesFromDatabase = moviesFromDatabase.Where(e => e.Title.ToLower().Contains(model.Keyword) ||
                                 e.Id.ToString() == model.Keyword || e.Year.ToString() == model.Keyword).ToList();
            }

            var dbMovieList = moviesFromDatabase.ToList();
            model.Records = dbMovieList.Select(e => new MovieModel(e)).ToList();

            return View(model);
        }

        public ActionResult SidebarPartial()
        {
            var model = new SideBarPartialModel()
            {
                Genres = new List<Models.GenreModel>(),
                RecentlyAdded = new List<Models.MovieListModel>()
            };

            var dbContext = new FbDatabase();
            model.Genres = dbContext.Genres.AsEnumerable().Select(e => new Models.GenreModel(e)).ToList();

            model.RecentlyAdded = dbContext.Movies.
                OrderByDescending(e => e.Id).Take(5).AsEnumerable().Select(e => new Models.MovieListModel(e)).ToList();

            return PartialView(model);
        }
    }
}

FilmBuffs/Controllers/MovieController.cs
using FilmBuffs.Models;
using FilmBuffs.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmBuffs.Controllers
{
    public class MovieController : BaseController
    {
        // GET: Movie
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(int id)
        {
            if (id > 0)
            {
                var dbContext = new FbDatabase();
                var entity = dbContext.Movies.FirstOrDefault(e => e.Id == id);
                if (entity != null)
                {
                    setPageTitle(entity.Title);

                    Session["MovieId"] = id;

                    return View(new MovieModel(entity));
                }
            }
            return Redirect("/");
        }
    }
}

FilmBuffs/Views/Home/Index.cshtml
@using FilmBuffs.Models
@model HomeModel
@{
    ViewBag.Title = Model.Heading;
}

<div class="panel panel-primary">
    <div class="panel-heading">

    </div>
    <div class="panel-body">
        <div class="exploremovie card border-dark mb-3">
            <a href="@Url.Action("Index", "Explore")" )><div class="card-header">Explore Movies</div></a>
            <br />
            @foreach (var movie in Model.Movies)
            {
                    <div class="container">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="@Url.Action("Detail", "Movie", new { id = movie.Id })">@movie.Title</a>
                            </h5>
                            <h6 class="card-subtitle mb-2 text-muted">@movie.Year</h6>
                            <p class="card-text">@Html.Raw(movie.Plot)</p>
                        </div>
                    </div>
                    <br />
                </div>             

            }


        </div>
    </div>
</div>

FilmBuffs/Views/Home/Search.cshtml
@using FilmBuffs.Models
@model SearchModel<MovieModel>

@{
    ViewBag.Title = "Search Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel-body">
    <div class="exploremovie card border-dark mb-3">
        <div class="card-header">Results</div>
        <br />
        @foreach (var movie in Model.Records)
        {
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="@Url.Action("Detail", "Movie", new { id = movie.Id })">@movie.Title</a>
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">@movie.Year</h6>
                        <p class="card-text">@Html.Raw(movie.Plot)</p>
                    </div>
                </div>
                <br />
            </div>

        }
    </div>
</div>

FilmBuffs/Views/Home/SidebarPartial.cshtml
@using FilmBuffs.Models
@model SideBarPartialModel
<div class="sidebar">
    
    <div class="genreview">   
        <div class="recently-viewed card border-dark mb-3" style="max-width: 27rem;">
            <div class="card-header">Explore Genres</div>
            <ul class="list-group">
                @foreach (var genre in Model.Genres)
                {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="@Url.Action("Index", "Home", new { area = "", id = genre.Id })">@genre.Name</a>
                </li>
                }
            </ul>
        </div>
    </div>

    <div class="recently-viewed">
        <div class="recently-viewed card border-dark mb-3" style="max-width: 27rem;">
            <div class="card-header">Recently Added</div>
            <ul class="list-group">
                @foreach (var movie in Model.RecentlyAdded)
                {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="@Url.Action("Detail", "Movie", new { id = movie.Id })">
                        @movie.Title
                    </a>
                </li>
                }
            </ul>
        </div>
    </div>
</div>